language: r
cache: packages
sudo: false
warnings_are_errors: false

install:
  - Rscript install-packages.R
  
script:
  - Rscript PortalForecasts.R

deploy:
  provider: script
  skip_cleanup: true
  script: deploy.sh
  on:
    branch: master
