language: r
cache: packages
sudo: false
warnings_are_errors: false

install:
  - Rscript install-packages.R
  - R -e 'download.file(url = "https://cran.r-project.org/src/contrib/Archive/tscount/tscount_1.3.0.tar.gz", destfile = "~/tscount_1.3.0.tar.gz")'
  - R -e 'install.packages(pkgs = "pkgFile", type = "source", repos = NULL)'
  
script:
  - Rscript PortalForecasts.R
